<?php
// Update Search Form Html
    function td_change_search_form( $form ) {
        $form = '
        <div class="search">
            <form role="search" method="get" id="search-form" action="' . home_url( '/' ) . '" >
                <label class="screen-reader-text" for="s">' . __('Search',  'domain') . '</label>
                <input type="search" value="' . esc_html(stripslashes_deep(get_search_query())) . '" name="s" id="s" placeholder="Search&hellip;" />
                <input type="submit" id="searchsubmit" value="'. esc_attr__('Go', 'domain') .'" />
            </form>
        </div>
        ';
        return $form;
    }
    add_filter( 'get_search_form', 'td_change_search_form' );
// SEARCH RESULTS
    // results count plugin
    # Define version number globally
    define ('results_count_version', '0.4.2');
    ### Search results count heading
    function wp_searchheader() {
            # Only display results where relevant
            if (is_search() || is_date() || is_category() || is_tag() || is_author()) {
            # Define global variables
            global $posts_per_page, $paged, $wp_query, $author_name, $author;
                # Calculate number of results, number of pages & current range.
                $numposts = $wp_query->found_posts;
                # Create formatted version of number for displaying
                if (0 < $numposts) $numposts_pretty = number_format($numposts);
                if(empty($paged)) {
                    $paged = 1;
                }
                $startpost = ($posts_per_page * $paged) - $posts_per_page + 1;
                if (($startpost + $posts_per_page - 1) >= $numposts) {
                    $endpost = $numposts;
                } else {
                    $endpost = $startpost + $posts_per_page -1;
                }
                # Add a comment in the html to show where the plugin generated code starts & ends)
                echo '<!-- The following post count code is automatically generated by the Results Count plugin version '.results_count_version.' : http://wordpress.org/extend/plugins/results-count/ -->';
                # Check if there is less than one page of results & alter text to suit
                if ($numposts>$posts_per_page) {
                        # Multiple pages of results
                        echo '<p>Showing results <b> '.$startpost. '</b> - <b>' .$endpost. '</b> of <b>' .$numposts_pretty. '</b>';
                    } else {
                    # Check if there is only a single result & alter text to suit
                        if ($numposts!=1) {
                        # Single page - multiple results
                            echo '<p>Showing <b>'.$numposts_pretty.'</b> results';
                        } else {
                            # Single result
                            echo '<p>Showing <b>'.$numposts_pretty.'</b> result';
                        }
                    }
                # Archive pages by date (display date range info).
                if (is_date()){
                    # Check if the date is a day, a month or a whole year.
                    if (is_day()) {
                        echo ' <b>';
                        the_time('l, F jS, Y');
                    }
                    elseif (is_month()) {
                        echo 'the month of <b>';
                        the_time('F, Y');
                    }
                    elseif (is_year) {
                        echo 'the year <b>';
                        the_time('Y');
                    }
                }
                # Archive pages by category (display category name).
                if (is_category()){
                    echo 'the category: <b><a href="http://', $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"], '">', single_cat_title(),'</a>';
                }
                # Archive pages by tag (display tag name).
                if (is_tag()){
                    echo 'the tag: <b><a href="http://', $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"], '">', single_tag_title(),'</a>';
                }
                        
                # Archive pages by author (display author name).
                if (is_author()){       
                    if(isset($_GET['author_name'])) :
                            $curauth = get_userdatabylogin($author_name);
                        else :
                            $curauth = get_userdata(intval($author));
                        endif;
                    echo 'the author: <b><a href="http://', $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"], '">', $curauth->nickname,'</a>';
                }
            # Close html tags.
            echo '</b>.</p>';
          echo '';
        }
    }
?>